apiVersion: apps/v1
kind: Deployment
metadata:
  name: titan-gateway
  namespace: "{{namespace}}"
  labels:
    app: titan-gateway
spec:
  replicas: {{gateway_replicas}}
  selector:
    matchLabels:
      app: titan-gateway
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  progressDeadlineSeconds: 120
  minReadySeconds: 30
  revisionHistoryLimit: 3
  template:
    metadata:
      name: titan-gateway
      labels:
        app: titan-gateway
    spec:
      nodeSelector:
        "{{gateway_nodelabel}}": "true"
      serviceAccountName: "{{service_account}}"
      containers:
        - image: "{{gateway_image}}"
          imagePullPolicy: "{{ gateway_pullPolicy }}"
          name: titan-gateway
          resources:
            limits:
              cpu: "{{ gateway_limit_cpu }}"
              memory: "{{ gateway_limit_memory }}"
            requests:
              cpu: "{{cpu_req}}"
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /v1/api/front/checkall
              port: {{gateway_port}}
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            exec:
              command:
                - "/bin/bash"
                - "-c"
                - result=`curl -k -sS http://127.0.0.1:{{gateway_port}}/v1/api/front/checkall 2>&1`; if [[ $result =~ 'abnormal_service":[]' ]]; then echo ok; else echo $result && exit 1; fi
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 3
          ports:
            - containerPort: {{gateway_port}}
              protocol: TCP
          command: ['/bin/sh', '-c', 'dockerize -secretdir /var/secrets/ -yaml-env /titan-env/titan-env.yml -template /titan-java-config/jaas_zk_client.conf:/data/app/titan-config/jaas_zk_client.conf -mergeToJson /titan-java-config/java.properties:/data/app/titan-config/java.json; chown -R titan:titan /data/app/titan-config; /data/app/titan-gateway/init.d/gateway start']
          volumeMounts:
            - name: var-secrets
              mountPath: /var/secrets/
            - name: titan-env
              mountPath: /titan-env
            - name: titan-java-config
              mountPath: /titan-java-config
            - mountPath: /data/titan-logs/java/gateway
              subPath: gateway
              name: titan-logs
            - name: tmp
              mountPath: /data/app/titan-gateway/tomcat
              subPath: tomcat
            - name: tmp
              mountPath: /tmp
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      volumes:
        - name: var-secrets
          secret:
            secretName: titan-all-secrets
        - name: titan-env
          configMap:
            name: titan-env
        - name: titan-java-config
          configMap:
            name: titan-java-config
        - emptyDir: {}
          name: tmp
