---
# tasks file for event-srv
- set_fact:
    work_nodes: "{{ label_nodes[eventsrv_nodelabel] }}"

- name: Print result
  debug:
    msg: "{{ work_nodes }}"

- fail:
    msg: "have no available node for event-srv"
  when: work_nodes|length <= 0

- name: Remove event-srv Deployment
  kubernetes.core.k8s:
    state: absent
    api_version: apps/v1
    kind: Deployment
    namespace: "{{ namespace }}"
    name: "titan-event-srv"

- name: create event-srv Deployment
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'eventsrv_deployment.yml' ) | from_yaml | titan_combine(common_patch,titanlogs_patch) }}"
    apply: yes

- name: create event-srv Service
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'eventsrv_service.yml' ) | from_yaml }}"
    apply: yes

