- name: get titan-wisteria
  kubernetes.core.k8s_info:
    kind: Deployment
    name: "titan-wisteria"
    namespace: "{{ namespace }}"
  register: tmp_setobj

- set_fact:
    tmp_ok: "{{tmp_setobj | deployment_check }}"

- set_fact:
    ok_app_roles: "{{ok_app_roles | union(['wisteria']) }}" 
  when: tmp_ok