apiVersion: v1
kind: Service
metadata:
  name: titan-web
  namespace: "{{namespace}}"
spec:
  selector:
    app: titan-web
  ports:
    - port: 80
      name: console
    - port: 81
      name: backend
    - port: 8000
      name: innerapi
    - port: 8001
      name: api
    - port: 8002
      name: agent
    - port: 8443
      name: upload