# 创建mongod服务
apiVersion: v1
kind: Service
metadata:
  name: "mongod-svc"
  namespace: "{{ namespace }}"
  labels:
    app: mongod-svc
spec:
  sessionAffinity: ClientIP
  ports:
    - name: mongod
      port: 27017
  selector:
    app: mongod