# 创建mongocs headless服务
apiVersion: v1
kind: Service
metadata:
  name: mongoshard{{shardseq}}-hs
  namespace: {{ namespace }}
  labels:
    app: mongoshard{{shardseq}}
spec:
  ports:
  - port: 27019
    name: mongoshard{{shardseq}}
  clusterIP: None
  selector:
    app: mongoshard{{shardseq}}