# 创建mongocs headless服务
apiVersion: v1
kind: Service
metadata:
  name: mongocs-hs
  namespace: {{ namespace }}
  labels:
    app: mongocs
spec:
  ports:
  - port: 27018
    name: mongocs
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: mongocs