# 创建mongocs headless服务
apiVersion: v1
kind: Service
metadata:
  name: mongos-hs
  namespace: {{ namespace }}
  labels:
    app: mongos
spec:
  ports:
  - port: 27017
    name: mongos
  clusterIP: None
  selector:
    app: mongos