---
# tasks file for connect-agent
- set_fact:
    work_nodes: "{{ label_nodes[connectagent_nodelabel] }}"

- name: Print result
  debug:
    msg: "{{ work_nodes }}"

- fail:
    msg: "have no available node for connectagent"
  when: work_nodes|length <= 0

- name: Remove connectagent Deployment
  kubernetes.core.k8s:
    state: absent
    api_version: apps/v1
    kind: Deployment
    namespace: "{{ namespace }}"
    name: "titan-connect-agent"

- name: create connectagent Deployment
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'connectagent_deployment.yml' ) | from_yaml | titan_combine(common_patch,titanlogs_patch) }}"
    apply: yes

- name: create connectagent Service
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'connectagent_service.yml' ) | from_yaml }}"
    apply: yes
