# 创建mongocs headless服务
apiVersion: v1
kind: Service
metadata:
  name: msmongod-hs
  namespace: {{ namespace }}
  labels:
    app: msmongod
spec:
  ports:
  - port: 27017
    name: msmongod
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: msmongod