# 创建mongod服务
apiVersion: v1
kind: Service
metadata:
  name: "msmongod-svc"
  namespace: "{{ namespace }}"
  labels:
    app: msmongod-svc
spec:
  sessionAffinity: ClientIP
  ports:
    - name: msmongod
      port: 27017
  selector:
    app: msmongod