# 创建mongocs headless服务
apiVersion: v1
kind: Service
metadata:
  name: msmongocs-hs
  namespace: {{ namespace }}
  labels:
    app: msmongocs
spec:
  ports:
  - port: 27018
    name: msmongocs
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: msmongocs