---
# tasks file for user-srv
- set_fact:
    work_nodes: "{{ label_nodes[usersrv_nodelabel] }}"

- name: Print result
  debug:
    msg: "{{ work_nodes }}"

- fail:
    msg: "have no available node for usersrv"
  when: work_nodes|length <= 0

- name: Remove usersrv Deployment
  kubernetes.core.k8s:
    state: absent
    api_version: apps/v1
    kind: Deployment
    namespace: "{{ namespace }}"
    name: "titan-usersrv"

- name: create usersrv Deployment
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'usersrv_deployment.yml' ) | from_yaml | titan_combine(common_patch,titanlogs_patch) }}"
    apply: yes

- name: create usersrv Service
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'usersrv_service.yml' ) | from_yaml }}"
    apply: yes
