- name: Remove zk StatefulSet
  kubernetes.core.k8s:
    state: absent
    api_version: apps/v1
    kind: StatefulSet
    namespace: "{{ namespace }}"
    name: "zk"

- name: Remove zk headless Service
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Service
    namespace: "{{ namespace }}"
    name: "zk-hs"

- name: Remove zk Service
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Service
    namespace: "{{ namespace }}"
    name: "zk-svc"

- name: Remove zk PodDisruptionBudget
  kubernetes.core.k8s:
    state: absent
    api_version: policy/v1beta1
    kind: PodDisruptionBudget
    namespace: "{{ namespace }}"
    name: "zk-pdb"

- name: Remove zk pvc
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: PersistentVolumeClaim
    namespace: "{{ namespace }}"
    name: "datadir-zk-{{index}}"
  loop: "{{ range(zk_replicas) | list }}"
  loop_control:
    loop_var: index

