---
# defaults file for redisphp
# 例如 redis_php_master_num为3,redis_php_slave_num为1时，master有3个实例，每个master有1个slave，共有 3+ 3×1 = 6个实例
# 所需最少节点数量 max(redis_php_master_num,redis_php_slave_num+1)
redis_php_master_num: 3
redis_php_slave_num: 2
redisphp_storage_capacity: "10Gi"
redisphp_hostpath: "/data/titan-container/redisphp/{0}"
redis_uid: 1000
redis_gid: 1000
redis_pullPolicy: IfNotPresent

redisphp_limit_memory: 4Gi
redisphp_req_memory: 128Mi