- name: get titan-patrol
  kubernetes.core.k8s_info:
    kind: Deployment
    name: "titan-patrol"
    namespace: "{{ namespace }}"
  register: tmp_setobj

- set_fact:
    tmp_ok: "{{tmp_setobj | deployment_check }}"

- set_fact:
    ok_app_roles: "{{ok_app_roles | union(['go-patrol']) }}" 
  when: tmp_ok