# 创建glusterfs headless服务
apiVersion: v1
kind: Service
metadata:
  name: glusterfs-hs
  namespace: {{ namespace }}
  labels:
    app: glusterfs-hs
spec:
  ports:
    - port: 24007
      name: tcp
    - port: 49152
      name: brick
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: titan-glusterfs