apiVersion: v1
kind: Service
metadata:
  name: titan-anti-virus-srv
  namespace: "{{namespace}}"
spec:
  selector:
    app: titan-anti-virus-srv
  ports:
    - protocol: TCP
      port: {{antivirussrv_port}}