---
# tasks file for connect-selector
- set_fact:
    work_nodes: "{{ label_nodes[connectselector_nodelabel] }}"

- name: Print result
  debug:
    msg: "{{ work_nodes }}"

- fail:
    msg: "have no available node for connectselector"
  when: work_nodes|length <= 0

- name: Remove connectselector Deployment
  kubernetes.core.k8s:
    state: absent
    api_version: apps/v1
    kind: Deployment
    namespace: "{{ namespace }}"
    name: "titan-connect-selector"

- name: create connectselector Deployment
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'connectselector_deployment.yml' ) | from_yaml | titan_combine(common_patch,titanlogs_patch) }}"
    apply: yes

- name: create connectselector Service
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'connectselector_service.yml' ) | from_yaml }}"
    apply: yes

