---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: titan-dfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: glusterfs.csi.qingteng.cn
    readOnly: false
    volumeHandle: titan-dfs
    volumeAttributes:
      server: glusterfs-hs
      share: /titan-glusterfs
