---
# defaults file for clusterlinksrv
clusterlinksrv_pullPolicy: IfNotPresent
clusterlinksrv_uid: 2020
clusterlinksrv_gid: 2020
clusterlinksrv_port: 6190

clusterlinksrv_limit_memory: 1Gi
clusterlinksrv_limit_cpu: 4
# Xmx设置，单位为M
clusterlinksrv_xmx: 512