- name: get titan-job-srv 
  kubernetes.core.k8s_info:
    kind: StatefulSet
    name: "titan-job-srv"
    namespace: "{{ namespace }}"
  register: tmp_setobj

- set_fact:
    tmp_ok: "{{tmp_setobj | statefulset_check }}"

- set_fact:
    ok_app_roles: "{{ok_app_roles | union(['job-srv']) }}" 
  when: tmp_ok