---
# tasks file for titan-clusterlink-srv
- set_fact:
    work_nodes: "{{ label_nodes[clusterlinksrv_nodelabel] }}"

- name: Print result
  debug:
    msg: "{{ work_nodes }}"

- fail:
    msg: "have no available node for clusterlink-srv"
  when: work_nodes|length <= 0

- name: Remove clusterlink-srv Deployment
  kubernetes.core.k8s:
    state: absent
    api_version: apps/v1
    kind: Deployment
    namespace: "{{ namespace }}"
    name: "titan-clusterlink-srv"

- name: create titan-clusterlink-srv Deployment
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'clusterlink-srv_deployment.yml' ) | from_yaml | titan_combine(common_patch,titanlogs_patch)  }}"
    apply: yes

- name: create clusterlink-srv Service
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'clusterlink-srv_service.yml' ) | from_yaml }}"
    apply: yes
