apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rabbitmq-peer-discovery-rbac
  namespace: "{{namespace}}"
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get","list","watch"]
# - apiGroups: [""]
#   resources: ["events"]
#   verbs: ["create"]