---
# tasks file for gateway
- set_fact:
    work_nodes: "{{ label_nodes[gateway_nodelabel] }}"

- name: Print result
  debug:
    msg: "{{ work_nodes }}"

- fail:
    msg: "have no available node for gateway"
  when: work_nodes|length <= 0

- name: Remove gateway Deployment
  kubernetes.core.k8s:
    state: absent
    api_version: apps/v1
    kind: Deployment
    namespace: "{{ namespace }}"
    name: "titan-gateway"

- name: create gateway Deployment
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'gateway_deployment.yml' ) | from_yaml | titan_combine(common_patch,titanlogs_patch) }}"
    apply: yes

- name: create gateway Service
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'gateway_service.yml' ) | from_yaml }}"
    apply: yes

