apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{service_account}}"
  namespace: "{{namespace}}"
automountServiceAccountToken: false
{% if use_registry_key %}
imagePullSecrets:
  - name: registry-key
{% endif %}