---
# tasks file for connect-dh
- set_fact:
    work_nodes: "{{ label_nodes[connectdh_nodelabel] }}"

- name: Print result
  debug:
    msg: "{{ work_nodes }}"

- fail:
    msg: "have no available node for connectdh"
  when: work_nodes|length <= 0

- name: Remove connectdh Deployment
  kubernetes.core.k8s:
    state: absent
    api_version: apps/v1
    kind: Deployment
    namespace: "{{ namespace }}"
    name: "titan-connect-dh"

- name: create connectdh Deployment
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'connectdh_deployment.yml' ) | from_yaml | titan_combine(common_patch,titanlogs_patch) }}"
    apply: yes

- name: create connectdh Service
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'connectdh_service.yml' ) | from_yaml }}"
    apply: yes
