---
# tasks file for ms-srv
- set_fact:
    work_nodes: "{{ label_nodes[mssrv_nodelabel] }}"

- name: Print result
  debug:
    msg: "{{ work_nodes }}"

- fail:
    msg: "have no available node for ms-srv"
  when: work_nodes|length <= 0

- name: Remove ms-srv Deployment
  kubernetes.core.k8s:
    state: absent
    api_version: apps/v1
    kind: Deployment
    namespace: "{{ namespace }}"
    name: "titan-ms-srv"

- name: create ms-srv Deployment
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'mssrv_deployment.yml' ) | from_yaml | titan_combine(common_patch,titanlogs_patch) }}"
    apply: yes

- name: create ms-srv Service
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'mssrv_service.yml' ) | from_yaml }}"
    apply: yes

