---
# tasks file for scan-srv
- set_fact:
    work_nodes: "{{ label_nodes[scansrv_nodelabel] }}"

- name: Print result
  debug:
    msg: "{{ work_nodes }}"

- fail:
    msg: "have no available node for scansrv"
  when: work_nodes|length <= 0

- name: Remove scansrv Deployment
  kubernetes.core.k8s:
    state: absent
    api_version: apps/v1
    kind: Deployment
    namespace: "{{ namespace }}"
    name: "titan-scan-srv"

- name: create scansrv Deployment
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'scansrv_deployment.yml' ) | from_yaml | titan_combine(common_patch,titanlogs_patch) }}"
    apply: yes

- name: create scansrv Service
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'scansrv_service.yml' ) | from_yaml }}"
    apply: yes
