---
# tasks file for connect-sh
- set_fact:
    work_nodes: "{{ label_nodes[connectsh_nodelabel] }}"

- name: Print result
  debug:
    msg: "{{ work_nodes }}"

- fail:
    msg: "have no available node for connectsh"
  when: work_nodes|length <= 0

- name: Remove connectsh StatefulSet
  kubernetes.core.k8s:
    state: absent
    api_version: apps/v1
    kind: StatefulSet
    namespace: "{{ namespace }}"
    name: "titan-connect-sh"

- name: create connectsh StatefulSet
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'connectsh_statefulset.yml' ) | from_yaml | titan_combine(common_patch,titanlogs_patch) }}"
    apply: yes

