apiVersion: v1
kind: Service
metadata:
  name: titan-connect-agent
  namespace: "{{namespace}}"
spec:
  selector:
    app: titan-connect-agent
  ports:
    - protocol: TCP
      port: {{connectagent_port}}