apiVersion: v1
kind: DaemonSet
metadata:
  name: license-code
  namespace: {{ namespace }}
spec:
  selector:
    matchLabels:
      app: license-code
  template:
    metadata:
      labels:
        app: license-code
    spec:
      nodeSelector:
        "{{connectagent_nodelabel}}": "true"
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: "{{service_account}}"
      containers:
        - name: license-code
          image: "{{sysinfo_image}}"
          imagePullPolicy: IfNotPresent
          resources:
              limits:
                memory: "100Mi"
              requests:
                cpu: "{{cpu_req}}"
                memory: "50Mi"
          command: ["tail", "-f", "/dev/null"]