# 创建mysql headless服务
apiVersion: v1
kind: Service
metadata:
  name: "mysql-hs"
  namespace: "{{ namespace }}"
  labels:
    app: mysql
spec:
  ports:
    - name: mysql
      port: 3306
    - name: mysql-galera
      port: 4567
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: mysql