# 创建mysql服务
apiVersion: v1
kind: Service
metadata:
  name: "mysql-svc"
  namespace: "{{ namespace }}"
  labels:
    app: mysql-svc
spec:
  sessionAffinity: ClientIP
  ports:
    - name: mysql
      port: 3306
  selector:
    app: mysql