---
ansible_user: root
server_init_args: >-
  {% if groups['master'] | length > 1 %}
    {% if ansible_host == hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) %}
    --cluster-init --token {{ k3s_token }} {{ extra_server_args | default('') }}
    {% else %}
    --server https://{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}:6443 --token {{ k3s_token }} {{ extra_server_args | default('') }}
    {% endif %}
  {% endif %}
